version: "3.9"
services:
  mysql:
    container_name: MySql_DB
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    networks:
      - app-network
    ports:
      - "${MYSQL_ROOT_PORT}:3306"
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql_data/db:/var/lib/mysql
    command: --init-file /docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    container_name: PhpMyAdmin
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
      - PMA_PORT=${PMA_CONNECT_PORT}
    ports:
      - "${PMA_ROOT_PORT}:80"
    depends_on:
      - mysql
    networks:
      - app-network
    volumes: 
      - phpMyAdminData:/var/www/html/libraries
      - phpMyAdminThemes:/var/www/html/themes

  api:
    container_name: GraphQL_Server
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    networks:
      - app-network
    ports:
      - "${API_PORT}:3001"
    env_file:
      - .env
    environment:
      - API_PORT=${API_PORT}
      - SECRET_SEED_KEY=${SECRET_SEED_KEY}
    depends_on:
      - mysql
    volumes: 
      - .:/app
      
networks:
  app-network:
    driver: bridge

volumes:
  phpMyAdminData:
  phpMyAdminThemes:
  .:
